** 30岁的我应该怎么办
    再一次站在人生的十字路口,不知道应该怎么应该怎么办,求教网友我应该怎么办
*** 个人情况说明

    本人男,今年30，单身，感情经历少，性格豪爽偏弱，有点轴，情商一般，逆商很高，普通一本，电子信息专业，长相路人，身高172，体形很壮，一般在150到160，毕业以后在上海做软件开发(大数据方向)，税后20k；同时也做投资从毕业到现在快6年了，目前有八成把握可以稳定年入12W；老家河南郑州农村，马路对面有一个中专，一个大专，父母年迈，今年70，上有三位姐姐，家里有父母盖的4层小楼，但是没有在郑州市区买房，也没有车，存款20多万。
*** 未来5-10年必定需要解决及面对的问题
    未来5-10年我必定需要解决及面对的问题是：
    1. 程序员的中年危机（主）
    2. 结婚生子
    3. 父母年迈
*** 出路
    针对以上问题，我觉得目前有4条路：
    1. 出国留学
    2. 继续在上海发展
    3. 回郑州
    4. 考公务员或老师
    5. 去老家马路对面的大专做老师
    6. 职业做交易（投资），在家陪父母
    7. 期待您的建议
*** 出国留学
    出国留学的事儿规划了3年，主要由于以下考虑：
    1. 延长程序员的职业生涯，有更好的职业发展空间
    2. 程序员做不了了，可以去国外做
    3. 避开外汇管制，投资我做的外盘，管制一紧就做不了了
    4. 更好的做投资，我是做外盘的，行情走势基本上都是跟着国外走的，不熟悉西方文化，国外的突发事件，你反应得不及时；国外的重大事件，你不理解为什么会这样
    5. 周围的同事，朋友基本上都是男的，30岁的生日刚刚过去，最近一年明显能感觉到长辈，朋友介绍的姑娘少了很多，而且有些是离异带孩子的（我才刚刚30，就已经这么不值钱了吗？我恋爱都没有怎么谈啊），出国留学应该会有更多的机会吧（我没有老牛吃嫩草的意思，年纪大了，更多的考虑不是青春靓丽，而是性格好）？就算不在国外找，回来再找，机会也更好吧？
    6. 谁不想见识下更广阔的世界，感受一下不同的文化呢？虽然这一点只是附带的。


    具体我是这么打算的：

    出国留学两年，学数据挖掘，回来以后继续做大数据，之前的工作经验没有丢，新的经历又可以用，职业生涯应该可以延长到40岁，然后可以去国外继续干，或者接私活，干到45岁以后，20年的投资经历转行职业做投资，把握不能再大了。至于出国留学的钱，自己的存款20多万；留学的时候还可以继续做投资，再保险一点，每个月赚8k；在澳大利亚正常打工，一个月也有1w不到，偶尔再接点软件方面的私活，绝对够，甚至还能存下来些，完全不用让父母掏钱。

    但是出国留学回来以后肯定是去北上广深，留在郑州太不划算，这样的话为父母考虑得就少了

    但是现在情况是：

    父母强烈反对：年纪太大，觉得离家太远，早该结婚生子了。
    大姐强烈反对：离家太远，风险太大，太不划算，投资有风险，你说你可以稳定月入1万，我怎么这么不信啊！
    二姐说:爸妈年纪大了，是不是觉得他们是你的负担？
    三姐说:个人情感支持，但是不提供任何资金支持（不反对我已经很高兴了）
    姨说：你钻到钱眼儿里了，爸妈都不要了；
    邻居说：你父母年纪这么大了，万一出个什么问题，离得这么远，你想好，别后悔！
    上海的领导说：我强烈建议你提升一下学历，太重要了，留学代价太大，可以读一下在职研究生，啊什么？你投资做这么好？那留学也可以
    上海深圳的朋友说：要是我的话我也想去，但是如果你去不了的话，就留在上海吧，等程序员干不动了，再回老家也不迟
    郑州的朋友说：学历只是一个敲门砖，你刚刚毕业的时候出去，回来能敲开绝大部分企业的门，但是你都30了，软件也做了5年了，现在企业看中的是你的技术，不是你的学历；
*** 留在上海
**** 规划
     继续老老实实地在上海做程序员，大概率是做到35岁之后不好做了，降低降低要求，做到37就结束了，然后回老家职业做投资，或者转行做其他的。
**** 考虑

     其实刚刚毕业的的两年，一直都是这么想的，觉得只要自己肯努力，努力工作，努力精进自己的技术，程序员的中年危机算什么啊，你技术精进了，精通某个技术，把底层原理吃透了，人家大专的，同样可以去阿里做技术总监

     但是慢慢地发现：
     1. 类似于阿里技术总监的职位就那么几个，程序员却有上千万，一门心思搞技术，不现实。
     2. 本科的就是本科的，硕士就是硕士，一眼就看出来了，但是技术好不好却是一个模糊的概念，尤其自己不善言辞，肚子里有东西也不容易倒出来。
     3. 技术也是有生命周期的，刚刚毕业的时候非常火的Spring-Struts-Hibernate，现在也就只有Spring依然坚挺。
     4. 技术依然是要练的，但是需要有人为你背书，比如说名企，名校，认可你的领导，还有自己的技术

*** 回到郑州
    昨天看了下郑州大数据的招聘情况，一共14条招聘信息，去掉长年打广告的， 去掉稳定军心的估计也就10条；去掉一个月前的，去掉招聘新手的，也就5条；去掉不发面试邀约的，去掉，最后面试通过的，估计也就一两个，

    简单来说，回郑州的话，薪资要减半，行情也远不如北京上海，就算面试通过，你也没得选！

    当然好处也很明显：离家更近了，压力也更小了

*** 做公务员或者老师
    这是邻居的建议，刚刚回家的时候，邻居问起，随口说准备回来发展，他们便说：木事儿，考公务员或者老师吧，国家的铁饭碗，个人是不想去的话，一来国家公务员考试/教师资格证考试就算通过，也不一定会分配到老家，二来做IT，一个月是这的六七倍，投资我随手下一单，也比这高。

*** 大专教书
    这是大姐的建议，个人不排斥，但是大专也是大学，我一普通本科的学历，肯定通过不了，就算能通过，也是养老的选项，对于现在的已经习惯995的自己来说太过清闲
    

*** 职业投资
    职业投资就无所谓工作地点了，天天呆在家里就行，但是职业投资风险太高，我职业做交易的朋友也不建议我这么搞。

     
*** 如何尽孝
    其实千言万语简化成一句话：如何平衡工作与家庭的问题：
    1. 是呆在老家，陪伴着父母？
    2. 在郑州工作，一个月回来一次？
    3. 在上海工作，三个月回来一次？
    4. 出国留学两年，半年回来一次？


    我问过很多人该怎么办，一个很实际的回答说不如留在上海。
    上海工作机会多，工资高，你年纪大了，老家和你差不多年纪的都结婚了，留在上海，认识姑娘的机会也多。你还要买房，买车，结婚生子。回老家了，你收入少了一半，消费却没少多少，怎么存钱？你还要买房，买车，还要结婚，将来结婚了，尤其是有了孩子之后，夫妻之间的矛盾绝大部分都是因为钱，有句话说得好：妻子有多温柔，取决于你收入有多高，这话不是没有道理。呆在父母身边不现实，而且时间久了容易闹矛盾，父母要求的不过是你过得好，然后有孙子抱，将来有了孩子，离家远不是问题，而且你不是投资做得还不错吗？万一，我是说万一哪一天父母病重，你完全可以把工作辞了，全职照顾父母。梦想再美好，还是要回归现实的。


*** 最后
    其实对于自己而言，规划了这么久，却去不了，就真的迷茫没有动力了，还不如留在郑州，结婚，生子，买房，买车，无所谓了。
