* 花间一壸酒独酌吾相亲
  题目很诗意,相亲的主题毫无诗意

   第一次相亲是在2014年
   记得那是2014年的夏天,应该是五一劳动节回家,正吃饭的时候一向对我溺爱非常地妈妈一脸严肃,用不容置喙的口吻说:"给你介绍了介姑娘,等下吃完饭和我一块出去一下。"
  任凭我怎么撒娇,怎么找托词,都逃不了妈妈慈爱的魔爪。唉，去就去吧。时光荏苒，5年的时光过去了，当初的情景，相亲的那位姑娘长什么样，说什么话，都已经不记得了，唯一记得的是那个明媚的下午我随着母亲悠闲缓慢地走在田间小道上，两边青翠的蒜苗在阳光下微风中轻轻地摇曳，母亲细心地叮嘱着每一个细节，我漫不经心地听着，只想着怎么尽快把母亲这毫无意义的活动打发了。
  第一次就是这么奇怪，印象很深，但是很深的却不是那个姑娘。

  后面姐姐介绍过，姑姑介绍过，伯母也介绍过。。。很多很多，但是都是只给一个电话或者微信让自己联系就完事儿了，那个时候刚刚到深圳，做的是软件，程序员的第一年，几乎每天都是下半夜回家，忙，却也只是不想联系的借口。更多是的对相亲的抗拒，以及高中无法解开的结。

  高中的时候，喜欢过一个姑娘，非常非常喜欢，屌丝爱上女神的故事，情事千差万别，但是却都殊途同归。
  现在想想，和知乎，微博不一样的是，她并没有世人口诛笔伐的作啊，情商低啊，现实啊什么的。相反，更多的却是发乎情，止乎礼。完全没有什么做得过分的地上，只是我第一次表白的结果太过意外，更多的是相距两地，我独自一人舐舔受伤的自己。
  16年春夏之交的一个早上，我和周老师照常去江湖公园跑步，跑完之后的大汗淋漓是最舒爽的。但是刚刚打开手机却看到她的婚讯，瞬间从头凉到底。自己呆呆地坐了好久，好久才反应过来：刚开始奋斗，目标却没了，呵呵
  说来也怪，在那之后就再也没有关注过，没有点开过她的朋友圈，没有了解过她的近况，更没有打过电话，发个祝福。那个梦回无数的姑娘，就像从来不曾来过自己的世界一样。
  时光继续流转，转瞬就到了2018年，没有人告诉自己今年会有血光之灾。不管是事业上的，投资上的，还是身体上的。有人把孤独分成了10级，2018还顺便体验了一把10级孤独。如果用词来描述自己，我觉得是勇者无惧，但是望着手术室的天花板，勇者真的无惧吗？自己真的是应该结束单身了。
  个人要求：
  不胖，不丑，聊得来
  最残的相亲直接被拉黑
  从心理上接受之后，三姐的学校正好来了一批新老师,正好趁着回家见了下。
  姑娘长得是挻高的，看着差不多有168，这是第一印象，也是唯一的印象，长相还行，大概6分，学历，家庭没在意。
  简单的寒暄之后，见面不到10分钟就借故离开了，当时还没有反应过来，回去之后发信息才发现自己被拉黑了。
  第一次相亲自己不重视，这一次自己重视了，却没有想到是这样的结果，没有问你人怎么样，工作怎么样，性格怎么样，仅仅见了一面，没什么深入的了解直接就把你给否了。
  真的挻受打击的。一直觉得自己长得不帅，但也不丑，但是那一刻，姑娘的感觉应该是这个人长得又黑又丑，还不高吧。

  最重视的相亲
  也是三姐学校的老师，初三的班主任，性格好，负责任，姐特别推荐。我特意推了去北京的出差，专门从上海回去老家。
  姑娘家不高不矮，长相贤淑，性格也挻好的，挻安静的一姑娘，看来姐看重她不是没有理由的。我们一块聊了很久，大部分时候教师我在说，未了，有学生打电话，她就回去。
  回去的路上我送她，她说：你人挻好的，只是我现在是班主任，有一个班的学生要中考，自己把99%的时间都拿来工作了，还怕做不好，不敢谈恋爱。
  看着她，我仿佛看到了2年前的自己，那个时间自己也是天天写代码写都下半夜，也是不怎么把恋爱的事儿放在心上。看来她和三姐是同事，大家一直工作碍于面子不好不来而已。
  既然无心，那就算了吧。

   那个离婚的姑娘
   发小的母亲介绍了个姑娘，离婚的。比我大2岁，看照片不胖，不丑。那段时间公司不好不忙，闲来无事聊了很多，结果发现挻聊得来的，
   跟其他认识的姑娘相比，她明显更知道自己想要找一个什么样的伴侣，不会diss男人的不忠，也不会diss社会对女子的不公。和她聊天是最舒服的，
   只是最终我还是介意她的离婚。

   突然发现她是好朋友的前女友
   这个是最遗憾的，只能放手
   初次见面是在浦东室友家里聚会认识的，期间一块吃饭，一块聊天，一块儿玩儿狼人杀，印象挻不错的。
   一次偶然的新年祝福，不知道为什么就聊了起来。因为家庭的原因她回老家当老师了，基本上每天都在微信上聊感情，人生，生活。
   就在即将确定关系的时候，却偶然之间知道她是我大学关系特好的同学Z的前女友！！！
   事情就是这么玄幻，尽管Z说没关系，他多次和我说他不介意，可是我介意，什么时候同学聚会了，太尴尬了！

   三观超正的姑娘
   人好，不丑，微胖，节俭，三观超正,有点懒，这是我对她的全部印象
   第一次见面，我们一块去一家餐厅，路有点远，我说要不叫个车吧，她说也不远啊，没事我们一起走过去吧。这话着实把我给惊了。
   一路上一直聊些有的没的，事儿不大，也琐碎，但是就是给人一种三观超正的感觉，见过的姑娘，没有之一。到了之后也是随便点了杯最便宜的奶茶。
   见面相亲姑娘不给男生个劲儿消费就算了，特意省钱的，还真是少见啊。印象不错，试试吧。
   几天之后，姐和妈问我对她的印象，我说挻好的，谈谈看吧。
   但是接下来姐和妈的话简直震碎了我的三观！既然觉得不错就尽快吧，你们好好谈谈，谈3个月差不多就提亲吧，到6月份就把婚事办了，也不能让人姑娘家等太久啊
   不知道为什么那一刻自己这些年出门在外所有的委屈瞬间涌上心来：我在深圳睡大街，被老板屌，天天加班到下半夜，投资被骗，金融失利亏得灵魂出窍，我所有的努力不是为了一个连恋爱都省了的婚姻！
   那一刻我决定放弃。

   19年春节的时候注册了相亲网站，遇见条件差不多的，心动的，就真心诚意地打招呼，只是没有想到自己花十几分钟写的消息，人家连回都不回。
   5月底的时候，告诉自己，最后一次，这一次我一定把她当成自己的真命追，追不上我就真的放弃了。
   这一次上天真的是和我开了一个莫大的玩笑，她真的是我的真命，我也真的把她当天命追，各种手段尽出，只是没有想到，最终也只是止步于聊天！

   这一次，我真的累了
   可能婚姻真的不适合我

   花间一壸酒,
   独酌吾相亲.
   举杯邀明月,
   对影成三人.
   月既不饮酒,
   徒影随我身.
   暂伴月将影,
   行乐须及春
   我歌月徘徊,
   我舞影零乱.
   醒时同交欢,
   醉后各分散.
   永结无情游,
   ...
