** 从医学的角度讲衰老与死亡
   本书作者从医生的角度讲述了大限将至的老人临终前几年的生活态度,生活质量,面临的生活困境,以及对现在发达的医疗技术(美国)的选择,所有种种最终反映一个问题:健康终将离去,大限终将来临,老人怎样有一个幸福的晚年.
   读了很多,印象异常深刻,尤其是以下几个方面:
   1. 我们都太年轻,身体都太健康,健康得让我们有一种错觉:自己是永生的
   2. 最美不过夕阳红只是晚年的开始,大限将至,老人是没有生活质量的
   3. 发达的医疗技术是为年轻人准备的,日渐衰老的身体根本承受不了手术,放疗,化疗的来回折腾
   4. 体验不一样的人生,思考死亡是为了省得更好
     
** 永生的错觉
   在人类10万年的存在史中,人类的寿命几乎从来都是不到30岁,自然的无数代选择决定了英年早逝是一个再正常不过的现象,而现在的悠久寿辰反而是下正常的.
   我们大部分人都身体健康,周围的朋友也都正值年壮.年少的无忧无虑,青春的肆意张扬,我们对未来充满了希望,为了工作透支身体,放纵酒色,忽视健康,仿佛自己注定永生一样,为了衰老和死亡对于我们来说是几十年后的事儿,这么遥远的时间,远得比我们过往的经历都要长, 长得我们甚至有一种永生的错误
   但是真的是这样吗?
   生命老化的故事其实就是身体器官走向衰竭的故事.
   人体最的物质是牙齿,却然后抵不到60年的悠悠岁月
   人体最有力量的是肌肉,但是随着时光的流逝,肌肉会损失40%
   骨骼是硬的,血管是软的,但是时间却会让骨质疏松,血管钙化
   生命为我们的很多器官做了双重备份,但是机器老了,终有报废的一天
   永生不过我们身体健康,正当年壮的错觉而已,终有一天我们会和所有的老人一样,蓦然之间发现自己曾经做了无数次的事情,习惯了,再正常不过的事情,却再也做不了了.
   比如说打篮球,跑两步不行了
   比如说不能独立吃饭,独立上厕所了,甚至不能独立走路了
   终有一天,我们会年纪大了
** 大限将至,老人没有生活质量
   曾经无数次设想过退休后的生活,种花,养狗,看书,息自己没有看去过的,没有玩儿过的,都玩儿玩儿,祖国的大好山河,都等着自己去开发.
   但是人老了最需要注意的就是走路,
   what? are you kidding me?,没错,就是走路,我们走了无数,跑了无数,最后最需要注意的就是走路.
   年轻的时候从来没有觉得走路对我们来说有什么困难的,但是人老了以后基本上都有骨质疏松,我们对走路早已习以为常,却不会注意到自己的身体已经不到了,
   哪一天万一跌倒了,天就塌了,而几乎每个老人的加速衰老都是从跌倒开始的!
   年轻的时候跌一跤没有关系,起来拍拍灰尘又和没事人一样,但是老人家的身体部件就像玻璃似的,而且人老都是先从腿开始老的,人老了身体的平衡感也差了.
   跌倒的机率自然就增加了.基本上跌倒一次后面第二次,第三次就跟着来了.
   
** 思考死亡是为了活得更好

   因为终有一死,闲来无事总会不自觉地想我是谁?我想成为谁?自己真正想要的是什么?
   因为终有一死,闲暇之内总会情不自禁地自问,自己应该怎样度过这有限的一生,
   《最好的告别》中根据作者的医疗经历,从病人确诊到死亡真的来临,一般有4个月的时间!
   很多年前的时候就听说过很多乔布斯和苹果的故事,印象最深的却是乔帮主的至理名言:把每一天都当成生命的最后一天.故里帮主每天早上都会自问:如果今天是此生最后一日,我今天要干些什么?无数次的反思自问,最终成就了今天价值万亿的苹果.作为一个程序员,乔帮主的至理名言我自然也把它奉为圭臬,无数次践行,无数次放弃,好多时候都不禁自问:这乔帮主把每天都当成征集的最后一天,那他是打造出iphone这一世纪爆款呢?怎么制定苹果的发展战略呢?
   4个月可以做很多事情,
   给父母打电话
   遇见一个姑娘, 告诉她我爱你
   开发一个让自己满意产品
   读本自己想读而很久没有读的书
   和至交好友开怀畅饮
   做自己一直想做却没有不敢做的事情
   ......
   4个月不长,也不短,正好可以把自己想做的事情做完
   那么为什么不把每一天都当做大限装至呢?

   唐宗宋祖,黄帝孔孟,开国圣祖,诗仙诗圣,穿越光泽的历史长河,走过相同的华夏大地,过程种种,在书中才能瞻仰的圣贤先知,无数代人迥然各异的生命轨迹,因为死亡,交汇在一起.
   生亦何欢,死亦何惧
   为生命找到重点,为人生确定主线,或许这就是死亡的意义
   
