** 教育类话题

*** 常考内容
 - 线上教育
 - 学校教育 VS 家庭教育
 - 实用科目 or 理论科目
 - 高中毕业是否要间隔一年上大学
 - 教育与就业
**** 相关短语
  | 中文               | 英文                                        |
  |--------------------+---------------------------------------------|
  | 家庭教育           | parenting                                   |
  | 远程教育           | online education / distance education       |
  | 学校教育           | schooling / formal education                |
  | 学术课程           | academic curriculum(s)                      |
  | 德育               | moral education                             |
  | 道德准则           | standard of morality                        |
  | 全面发展           | comprehensive / all-around development      |
  | 补充               | complement                                  |
  | 各种途径来获取知识 | acquire knowledge from different approaches |
  | 知识的良好掌握     | good command of knowledge                   |
  | 开阔眼界           | broaden the horizon                         |

*** 线上教育的优点
    1. 灵活自由(flexible and free):
       1. 克服地域障碍(overcome geographical limitation)
       2. 任何时间任何地址(anytime and anywhere)
    2. 减轻经济负担(ease the financial burden):
       1. 成本低,经济(low cost and economical)
       2. 只需要有网络就可以实现(be done through network)
    3. 效率高(high efficiency)
       1. 节省大量路上时间(save time on commuting)

*** 在学校住的好处
    1. 更安全(safer)
       1. 学校有良好,完善的安保系统(perfect security system), 比如:闭路电视(CCTV),保安(security)等
    2. 有利于建立友谊(be beneficial to build up friendship)
       1. 宿舍中都是同学,大家有更多机会相识(more opportunities to meet each other),并且相互沟通和交流
    3. 提高学习和生活效率(improve the efficiency of study and life)
       1. 宿舍通常在校园里,学生更容易使用学校各种资源(easily access to school resources);
       2. 可以省中止的时间,更方便
**** 相关短语
     | 中文           | 英文                       |
     |----------------+----------------------------|
     | 培养社交能力   | develop social ability     |
     | 融入社会       | integrate into the society |
     | 学习氛围       | learning atmosphere        |
     | 与...合作      | cooperate with             |
     | 团队精神       | team spirit                |
     | 人际关系的能力 | interpersonal skill        |
     | 独立思考的能力 | independent thinking       |
*** 实用科目 or 理论科目
    1. (大学)学校应该教授对工作实用的课程(practical subjects, such as computer science, management)
       1. 掌握实用的学科和技能(practical subjects and skills)
       2. 可以帮助学生求职(improve career)
    2. (大学)学校应该注重理论学科(theoretical knowledge)
       1. 学好理论学科可以为实用性的学科和技能打下扎实的基础(a strong background in certain academic subjects can lay solid foundations for practical subjects and skills)
    3. (大学)一些大学里的专业需要更深的学术研究,比如(philosopher,需要理论性知识更多的专业(major)
**** 相关短语
     | 中文           | 英文                       |
     |----------------+----------------------------|
     | 通才教育       | a well-rounded education   |
     | 产生厌倦的情绪 | be fed up with             |
     | 书呆子         | book worms                 |
     | 想象力与创造力 | imagination and creativity |
     | 社会经验       | social experience          |
*** 为什么要间隔一年
    1. 间隔一年可以给学生一年的时间休息(one-year break),并且思考自己到底喜欢什么,从而帮助树立职业定位
    2. 间隔一年可以来缓解大学学习生活的经济压力(relieve the financial burden)
    3. 积累社会经验(accumulate social experience),更好地融入当前社会(integrate into society)

**** advantages of overseas study
     - ambition and desire to learn 雄心和学习的热望
     - cultivate the ability of self-learning 培养自觉能力
     - expand their knowledge 扩展知识
     - build up the friendship 建立友谊
     - sense of cooperation and competition 使用与竞争精神
     - broaden their horizon 开阔眼界
     - team spirit 团队精神
     - sense of right and wrong 辨别是非
     - creation and originality 创造力与独创性
     - trustworthy 值得信赖
     - independent effort rather than being spoonfed 独立能力而非依赖于人
     - farsighted instead of being shortsighted 卓识远见而非目光短浅
     - remove loneliness and disorientation 消除孤独感和不适应感
     - cross-cultural communication 跨文化交际
**** 国际援助话题
     教育是解决相应问题的一个途径(分析解决型题目),把教育作为一些话题的解决方案
     国际援助话题 -- 除经济援助(financial aid) 外,还可以通过教育方式的援助
     教育的援助会发挥很大的作用(make a huge difference), 因为这有有利于贫困地区的可可持续发展(educational aid is a sustainable development)
**** 尊敬老年人,教师话题(students' poor bahavior)
     学生应该尊重师长(shold be educated to respect the old and teachers),
     这方面提倡家庭的教育和引导(parental education and guidance is recommended)
**** 大学生就业难的话题
     工作难的一个原因可能是没有接受良好的教育(fail to secure a decent job because of the poor education)
     因而学生应该接受教育和工作培训,提升就业机会(receive good educatin and training program to increase the chances)
**** 青少年犯罪话题
     some youngsters embark on the criminal road
     offer them adequate education
**** 环境问题
     enhance the awareness of environmental protection
**** 解决交通问题
     增强人们的案值意识及遵守交通规则(cultivate the sense of safety, be educated to respect the traffic rules)
**** 范文
     In some countries, there has been an increase in the number of parents who educate their children themselves at home instead of sending them to school. do you think the advantages of this outweight the disadvantages?
** 动物类话题
*** 常考内容
    - 动物实验
    - 动物与人
    - 保护动物的意义
    - 保护动物措施
*** 有关动物实验
    1. 不人道(inhumane)
       科学实验,比如:医学实验medical research,临床研究clinical research,都会先给动物实验,其行为残忍和野蛮(cruel and barbaric
    2. 推动医学进步(promote medical breakthroughs)
       每个人都从动物实验中获益(every human has benefited directly
       有些实验是为了研制疫苗(vaccine, 来预防和治疗cure一些危及人类生命的疾病life-threatening diseases
    3. 动物应该有生存权(animal rights)
       很多动物会受尽折磨最终死亡result in suffering or death
       人道最基本原则是对于自然的爱心the most basic principle of humanity is the love to nature
    Agree:
    1. inhumane:对动物的折磨(torture),其行为是残忍和野蛮的(cruel and barbaric)
    2. 动物也有生存的权利(animal rights),应该与人类共存(co-existence).在自然界中,应该尊重所有生物生存的权利(right to live),要实现万物的共存(live and let live)
    Disagree:
    1. 节约成本 economical some are easily bred
    2. 没有别的可以替代的方式 only reliable method for nowadays
    3. 推动医疗进步 promote medical progress
**** 相关短语
     | 中文               | 英文                           |
     |--------------------+--------------------------------|
     | 残忍地对待动物     | cruel treatment of animals     |
     | 电脑模拟           | computer model                 |
     | 虐待动物           | animal abuse                   |
     | 头等野生运行的环境 | wildlife-friendly environment  |
     | 在动物身上做实验   | perform experiments on animals |
     | 可替代的方式       | alternative methods            |
     | 生存的权利         | right to live                  |
*** 动物与人
    1. 动物是人们的好朋友(good friends of mankind)
       动物是生态系统中不可缺少的一部分(an indispensable part in nature).
       我们应该要和动物共存(coexistance),
       和谐地生活(live harmoniously)在这个地球上
    2. 动物培训孩子的爱心(cultivate children's love and care)
       动物有助于培养孩子们对大自然的热爱(nurture the love for nature),责任心(sense of responsibility)和独立精神(independence).
    3. 帮助人们驱逐孤独(drive off the loneliness)
       尤其是对于很多的老人,退休之后(after retirement),子女不在身边,他们通过养小动物,比如:猫和狗来陪伴自己,减轻孤独与寂寞(feel less loneliness)
**** 相关短语
     | 中文           | 英文                                   |
     |----------------+----------------------------------------|
     | 人与动物的需要 | balance the needs of human and animals |
     | 同情           | compassion                             |
     | 饲养宠物       | raise pets                             |
     | 家人           | family member                          |
     | 物种繁殖的场所 | a place ofr the breeding               |
     | 濒危动物       | endangered animals                     |
*** 保护动物措施
    - 法律惩罚(law):加重对虐待动物行为的处罚(propose heavier penalties on animal abuse
    - 媒体号召(media):引起社会关注一连串动物被虐待及残杀的事件arouse public concern on animal abuse
    - 必须做的试验,要尽量动物的痛苦:
      animal testing should cause as little suffering as possible;
      animal tests should only be performed where necessary
*** 范文
    some people argue that too much attention and too many resources are given to he protection of wild animals and birds. To what extent do you agree or disagree?
    In recent years, animal protection has become an issure of concern.
    People take different attitueds toward the increasing attention and expenditure on wildlife conservation.Some people suggest that the spending should be redirected to helping other fields in our society. I agree with the view that the investment in wildlife protection is not worthwhile.

    Animals, as a key component of the whole food chain, hvae a profound impact on the sustainability of an ecosystem. as we known, every kind of animals plays an important role in natural balance. For instance, the demise of any species will lead to the growth or decline of other species. In some extreme cases, some species may at the verge of extincting such as Dodo bird. If people did not take action to protect wildlife as soon as possibel, we humans would be affected in the end.

    However, there are more issues that we need to focus in our society rather than protecting animals.In current social context, the primary task is still to improve living standards since there are many people living under the poverty line. Only when people are in a good living condition can they pay attention to other social problems.Besides,technology and education are another two aspects for governments to concern.These two industries accelerate the development of society, which will provide a better protection for wildlife in turn

    In conclusion, although the animal is a significant part of ecosystem, it is better for governments to invest more finance and resources in other social problems

